schema_version = "1.0.0"

id = "CAD_Sketcher"
version = "0.27.3"
name = "CAD Sketcher"
tagline = "Parametric, constraint-based geometry sketcher"
maintainer = "hlorus <dave19924@gmail.com>"
type = "add-on"

permissions = ["files", "network"]

website = "https://www.cadsketcher.com/"

tags = ["3D View", "Modeling", "Mesh", "Object"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
